dist: xenial

language: python
python:
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10-dev'

jobs:
  fast_finish: true
  allow_failures:
    - python: '3.10-dev'

before_install:
  - python --version
  - pip install --upgrade pip
  - pip install codecov

install:
  - make install

script:
  - make test-cov-xml

after_success:
  - codecov

